version: 2.1

executors:
  yuki-builder:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/lesnuages/yuki

jobs:
  build:
    executor: yuki-builder
    steps:
      - checkout
      - run: sudo apt update && sudo apt install libpcap-dev
      - run: go get github.com/desertbit/grumble
      - run: go get github.com/google/gopacket
      - run: go get github.com/mdlayher/raw
      - run: go get github.com/olekukonko/tablewriter
      - run: go build -o yuki yuki.go

      - persist_to_workspace:
          root: /go/src/github.com/lesnuages/
          paths:
            - yuki/*
  
  publish-github-release:
    executor: yuki-builder
    steps:
      - attach_workspace:
          at: /go/src/github.com/lesnuages/yuki
      - run:
          name: "Publish Release on GitHub"
          command: |
            sudo apt update && sudo apt install libpcap0.8
            go get github.com/tcnksm/ghr
            cd /go/src/github.com/lesnuages/yuki/
            VERSION=$(./yuki/yuki --version) 
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_CI_PROJECT_USERNAME} -r ${CIRCLE_CI_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /go/src/github.com/lesnuages/yuki/yuki/

workflows:
  version: 2.1
  build-and-publish:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/